### ISSUE TITLE
http 和 rmi 都连不上，cannot connect to ('0.0.0.0', 7766): [WinError 10049]

### ISSUE THREAD

**Issue by Chenchen123456789** [YQBaobao/openopc-python3.8#1]
cannot connect to ('0.0.0.0', 7766): [WinError 10049]

**Comment by Chenchen123456789** [comment]
大佬你能连上吗，windows更新以后

**Comment by YQBaobao** [comment]
需要先在服务器端启动相关的服务，如http,
http不受系统更新影响




yqbaowo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YQBaobao/openopc-python3.8"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月31日(星期三) 晚上8:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [YQBaobao/openopc-python3.8] http 和 rmi 都连不上，cannot connect to ('0.0.0.0', 7766): [WinError 10049] (Issue #1)





 
大佬你能连上吗，windows更新以后

**Comment by YQBaobao** [comment]
> cannot connect to ('0.0.0.0', 7766): [WinError 10049]无法连接到（'0.0.0.0'，7766）：[WinError 10049]

需要先在服务器端启动相关的服务，如http,
均不受系统更新影响

**Comment by YQBaobao** [comment]
你确定已经启动了相关的服务了吗？并且需要开放防火墙的端口：7766

**Comment by YQBaobao** [comment]
> cannot connect to ('0.0.0.0', 7766): [WinError 10049]

1. 你如果需要使用 `rmi `服务，需要先将 `bin `目录复制到OPC服务器端，然后执行` service-insatll.bat`  ，最后才能使用 `rmi `客户端连接
2. 你如果使用 `http` 服务，同理也需要先将 `bin `目录复制到OPC服务器端，然后先后执行 `name-service-insatll.bat`与`http-gateway-start.bat`，这两个文件，最后才能使用 `http `客户端连接
3. 注意： `rmi `服务 与 `http` 服务使用一个即可，并且需要开放防火墙端口，`rmi `服务端口 `7766`， `http` 服务端口 `7767`

**Comment by Chenchen123456789** [comment]
谢谢大佬，我之前用你的opc.exe测试的mode open，然后报的这个错，后来在代码里用open_client(127.0.0.1, 7766)就通了。

**Comment by YQBaobao** [comment]
不客气

> 谢谢大佬，我之前用你的opc.exe测试的mode open，然后报的这个错，后来在代码里用open_client(127.0.0.1, 7766)就通了。

**Comment by Chenchen123456789** [comment]
大佬请教一个问题，你的那个openopc库怎么使用订阅功能。

**Comment by YQBaobao** [comment]
不好意思，现在才看到，不过你说的这个订阅，是指的订阅什么内容？

**Comment by YQBaobao** [comment]
> 大佬请教一个问题，你的那个openopc库怎么使用订阅功能。 Message ID: ***@***.***&gt;
不好意思，现在才看到，不过你说的这个订阅，是指的订阅什么内容？

**Comment by YQBaobao** [comment]
> 大佬请教一个问题，你的那个openopc库怎么使用订阅功能。 Message ID: ***@***.***&gt;

你指的订阅，是订阅什么内容？
