### ISSUE TITLE
rmi服务内存持续增长问题，一直持续读数据

### ISSUE THREAD

**Issue by Chenchen123456789** [YQBaobao/openopc-python3.8#2]
rmi服务内存持续增长问题，一直持续读数据，1s一次，跑了一夜，服务内存涨到1.6g了，请问大佬怎么优化。
![1710554681523 - 副本](https://github.com/YQBaobao/openopc-python3.8/assets/40755016/3320c2d9-7b54-4889-a25f-b56871c74af2)

**Comment by YQBaobao** [comment]
你具体是怎么做的？怎么复现？

**Comment by Chenchen123456789** [comment]
是我read传的参数不对，现在试出来了
